export const MASTER_PAGE_CONFIG = {
  role: {
    resource: "roles",
    idPrefix: "role",
    title: "Role Master",
    createButtonLabel: "Create Role",
    createFormTitle: "Create Role",
    updateFormTitle: "Update Role",
    nameLabel: "Role Name",
    descriptionLabel: "Role Description",
    searchPlaceholder: "Search by role name or description",
    emptyMessage: "No roles found.",
    loadErrorMessage: "Failed to load roles.",
    saveErrorMessage: "Failed to save role.",
    deleteErrorMessage: "Failed to delete role.",
    deleteConfirm: (name) => `Do you want to delete role "${name}"?`,
  },
  clientType: {
    resource: "client-types",
    idPrefix: "client-type",
    title: "Client Type",
    createButtonLabel: "Create Client Type",
    createFormTitle: "Create Client Type",
    updateFormTitle: "Update Client Type",
    nameLabel: "Client Type Name",
    descriptionLabel: "Client Type Description",
    searchPlaceholder: "Search by client type name or description",
    emptyMessage: "No client types found.",
    loadErrorMessage: "Failed to load client types.",
    saveErrorMessage: "Failed to save client type.",
    deleteErrorMessage: "Failed to delete client type.",
    deleteConfirm: (name) => `Do you want to delete client type "${name}"?`,
  },
  caseType: {
    resource: "case-types",
    idPrefix: "case-type",
    title: "Case Types",
    createButtonLabel: "Create Case Type",
    createFormTitle: "Create Case Type",
    updateFormTitle: "Update Case Type",
    nameLabel: "Case Type Name",
    descriptionLabel: "Case Type Description",
    searchPlaceholder: "Search by case type name or description",
    emptyMessage: "No case types found.",
    loadErrorMessage: "Failed to load case types.",
    saveErrorMessage: "Failed to save case type.",
    deleteErrorMessage: "Failed to delete case type.",
    deleteConfirm: (name) => `Do you want to delete case type "${name}"?`,
  },
  status: {
    resource: "statuses",
    idPrefix: "status",
    title: "Status",
    createButtonLabel: "Create Status",
    createFormTitle: "Create Status",
    updateFormTitle: "Update Status",
    nameLabel: "Status Name",
    descriptionLabel: "Status Description",
    searchPlaceholder: "Search by status name or description",
    emptyMessage: "No statuses found.",
    loadErrorMessage: "Failed to load statuses.",
    saveErrorMessage: "Failed to save status.",
    deleteErrorMessage: "Failed to delete status.",
    deleteConfirm: (name) => `Do you want to delete status "${name}"?`,
  },
  court: {
    resource: "courts",
    idPrefix: "court",
    title: "Court",
    createButtonLabel: "Create Court",
    createFormTitle: "Create Court",
    updateFormTitle: "Update Court",
    nameLabel: "Court Name",
    descriptionLabel: "Court Description",
    searchPlaceholder: "Search by court name or description",
    emptyMessage: "No courts found.",
    loadErrorMessage: "Failed to load courts.",
    saveErrorMessage: "Failed to save court.",
    deleteErrorMessage: "Failed to delete court.",
    deleteConfirm: (name) => `Do you want to delete court "${name}"?`,
  },
};
